### ISSUE TITLE
[Passive] Candle Kit

### ISSUE THREAD

**Issue by Meowlala** [FacemanFoothand/TeamAlpha#17]
Summons two candles that orbit Isaac, hurting and burning enemies they touch.

"Don't burn it at both ends"

Assets:
![icon_candlekit](https://cloud.githubusercontent.com/assets/24993635/21793991/82762a74-d6b3-11e6-9ad2-21f5a5a821d5.png)

Sprite: Complete
![](https://cdn.discordapp.com/attachments/267354052009000961/268096721832116227/unknown.png)

Pause Art: Complete

Animation: Orbitals, currently code being worked on.

Code: Haulted

Test Notes: No familiar.Orbit() function exists so all movement has to be done manually frame by frame.
Animation is named Idle

**Comment by mikemedina** [comment]
Before all this animation work goes in, has anyone tried extending the parent entities of other orbitals like Cube of Meat and Sacrificial Dagger?

I haven't looked into this at all (I'm at work) but I'd hate to see a bunch of work go into animation if this behavior is extendable already.

**Comment by FacemanFoothand** [comment]
TODO:

1. Figure out how to code an orbital behavior for the candles.
2. Upon enemy contact the orbitals deal damage to enemies.
3. Orbitals will orbit at a larger radius than normal and not block shots.

**Comment by Meowlala** [comment]
Finished!
