### ISSUE TITLE
[Passive] Cologne

### ISSUE THREAD

**Issue by FacemanFoothand** [FacemanFoothand/TeamAlpha#2]
Creates an aura around Isaac that has a chance to charm enemies.

"Rhymes with alone..."

Assets:
![icon_cologne](https://cloud.githubusercontent.com/assets/24993635/21793463/d8aa8034-d6ae-11e6-98a5-033aa9775b91.png)
![cologne](https://cloud.githubusercontent.com/assets/24993635/21793466/ddeec118-d6ae-11e6-9b73-b5ace2eee938.png)

Sprite: Completed

![cologne](https://cloud.githubusercontent.com/assets/24993635/21753606/ca37566e-d5ad-11e6-99bf-446376b3409c.png)

Pause Art: Complete

Costume: Complete

![](https://cdn.discordapp.com/attachments/267672001253081088/268144019282984960/Screen_Shot_2017-01-09_at_5.27.52_PM.png)

Code: Complete

Testing Notes: Increase effect radius.

**Comment by mikemedina** [comment]
Just need the spritesheet and this should be marked as complete

**Comment by FacemanFoothand** [comment]
@origamidragon Can you please upload the sprite sheet file to dropbox? Thanks! I believe I already msged you on Discord but I am using this now much more effectively :)
